backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "إعدادات الموقع"
    files:
      - file: "content/settings.json"
        label: "إعدادات عامة"
        name: "settings"
        fields:
          - {label: "اسم الشركة", name: "company_name_ar", widget: "string"}
          - {label: "رقم الهاتف", name: "contact_phone", widget: "string"}
