backend:
  name: git-gateway
  branch: main # تأكد أن هذا هو اسم الفرع الرئيسي لديك

media_folder: "images" # المجلد الذي تحفظ فيه صورك
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html" # ملف الصفحة الرئيسية
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Text", name: "body", widget: "markdown"}
